/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package connect4;

/**
 *
 * @author janhaeberle
 */
class Point
{
    // This code was generated by a tool.
    int x;
    int y;
    int state;
    
    Point(int xt, int yt, int statet)
    {
        x=xt;
        y=yt;
        state=statet;
    }
    /**
     * 
     * @param q
     * @return 
     */
    boolean equalsPosition(Point q)
    {
        return x==q.x && y==q.y;
    }
    
    void setState(int player)
    {
        state=player;
    }
    
    int getState()
    {
        return state;
    }
    
}